#URLs
URL_GET_PETMATCHES_JSON = "/matching/get_PetMatches_JSON"
URL_PMDP = '/matching/'
URL_GET_CANDIDATE_PETREPORTS_JSON="/matching/get_candidate_PetReports_JSON"
URL_VOTE_PETMATCH = '/matching/vote/'
URL_MATCHING = "/matching/new/"
URL_PROPOSE_PETMATCH = "/matching/propose/"

HTML_PMDP = "matching/petmatch.html"
HTML_MATCHING = "matching/matching.html"
HTML_PROPOSE_MATCH = "matching/propose_petmatch.html"

#PetMatch Constants
PETMATCH_OUTCOME_NEW_PETMATCH = "NEW PETMATCH"
PETMATCH_OUTCOME_DUPLICATE_PETMATCH = "DUPCLIATE PETMATCH"
PETMATCH_OUTCOME_UPDATE = "SQL UPDATE"
PETMATCH_OUTCOME_INSERTED_IMPROPERLY = "INSERTED IMPROPERLY"

PETMATCH_DESCRIPTION_LENGTH = 300
PETMATCH_VERIFICATION_VOTES_LENGTH = 2

#Identifiers
UPVOTE = "upvote"
DOWNVOTE = "downvote"

#number of pet matches on the home page
NUM_PETMATCHES_HOMEPAGE = 25
