# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-17 13:21
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EditUserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activation_key', models.CharField(max_length=40, null=True)),
                ('date_of_change', models.DateTimeField(default=django.utils.timezone.now)),
                ('new_email', models.EmailField(max_length=254, null=True)),
                ('user', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dob', models.DateField(default=datetime.date(2016, 8, 17))),
                ('img_path', models.ImageField(default=b'userprofile/uploads/defaults/anonymous.gif', null=True, upload_to=b'userprofile/uploads/')),
                ('thumb_path', models.ImageField(default=b'userprofile/thumbnails/defaults/anonymous.gif', null=True, upload_to=b'userprofile/thumbnails/')),
                ('last_logout', models.DateTimeField(auto_now_add=True, null=True)),
                ('reputation', models.FloatField(default=0, null=True)),
                ('description', models.CharField(default=b'', max_length=300, null=True)),
                ('social_profile', models.BooleanField(default=False)),
                ('is_minor', models.BooleanField(default=False)),
                ('guardian_consented', models.BooleanField(default=False)),
                ('guardian_email', models.EmailField(default=None, max_length=254, null=True)),
                ('guardian_activation_key', models.CharField(max_length=40, null=True)),
                ('following', models.ManyToManyField(related_name='followers', to='socializing.UserProfile')),
                ('user', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
