import os
from project.settings import STATIC_URL
'''===================================================================================
[constants.py]: Constants for the EPM system
==================================================================================='''

#Number of Tests
NUMBER_OF_TESTS = 10

#Lower and Upper bounds for Lost and Found Dates
DATE_LOWER_BOUND = "2012-01-01"
DATE_UPPER_BOUND = "2012-08-16"

#number of pet reports on the home page
NUM_PETREPORTS_HOMEPAGE = 50
#number of pet matches on the home page
NUM_PETMATCHES_HOMEPAGE = 25
#number of bookmarks on the home page
NUM_BOOKMARKS_HOMEPAGE = 50


#Enums for Various Model Choice Fields
PET_TYPE_CHOICES = [('Dog', 'Dog'), ('Cat', 'Cat'), ('Bird', 'Bird'), ('Horse', 'Horse'), ('Rabbit', 'Rabbit'), ('Snake', 'Snake'), ('Turtle', 'Turtle'), ('Other', 'Other')]
STATUS_CHOICES = [('Lost','Lost'),('Found','Found')]
SEX_CHOICES=[('M','Male'),('F','Female')]
SIZE_CHOICES = [('XL', 'Extra Large'),('L', 'Large'), ('M', 'Medium'), ('S', 'Small')]
SPAYED_OR_NEUTERED_CHOICES = [("Not Known", "Not Known"),('Spayed', 'Spayed'), ('Neutered', 'Neutered'), ("Neither", "Neither")]
AGE_CHOICES = [('Baby','Baby'),('Young','Young'),('Adult','Adult'),('Senior','Senior'),("Not Known", "Not Known")]

#max_length for Model Fields
USER_USERNAME_LENGTH = 30
USER_FIRSTNAME_LENGTH = 30
USER_LASTNAME_LENGTH = 30
USER_PASSWORD_LENGTH = 30
PETREPORT_PET_TYPE_LENGTH = 10
PETREPORT_STATUS_LENGTH = 5
PETREPORT_SEX_LENGTH = 6
PETREPORT_SIZE_LENGTH = 30
PETREPORT_LOCATION_LENGTH = 100
PETREPORT_PET_NAME_LENGTH = 15 
PETREPORT_MICROCHIP_ID_LENGTH = 40
PETREPORT_TAG_INFO_LENGTH = 500
PETREPORT_CONTACT_NAME_LENGTH = 20
PETREPORT_CONTACT_NUMBER_LENGTH = 15
PETREPORT_CONTACT_EMAIL_LENGTH = 30
PETREPORT_AGE_LENGTH = 10
PETREPORT_COLOR_LENGTH =30
PETREPORT_BREED_LENGTH = 30
PETREPORT_DESCRIPTION_LENGTH = 1000
PETREPORT_SPAYED_OR_NEUTERED_LENGTH = 10
PETMATCH_DESCRIPTION_LENGTH = 300
PETMATCH_VERIFICATION_VOTES_LENGTH = 2
CHATLINE_TEXT_LENGTH = 10000

#Small List of Names
USERNAMES = ['Jacob', 'Emily', 'Joshua', 'Madison', 'Kenneth', 'Mark', 'Dave', 'Angela', '' 'Matthew', 'Olivia', 'Daniel', 'Hannah', 
'Chris', 'Abby', 'Andrew', 'Isabella', 'Mario', 'Sahar', 'Amrutha', 'Leysia', 'Ken', 'Abe']
PETREPORT_NAMES = ['Sparky', 'Nugget', 'Sydney', 'Missy', 'Marley', 'Fousey', 'Daisy', 'Libby', 'Apollo', 'Bentley', 'Scruffy',
'Dandy', 'Candy', 'Mark', 'Baby', 'Toodle', 'Princess' ,'Prince', 'Guss']

#PetReport Image constants
PETREPORT_THUMBNAIL_WIDTH = 128
PETREPORT_THUMBNAIL_HEIGHT = 128
USERPROFILE_THUMBNAIL_WIDTH = 128
USERPROFILE_THUMBNAIL_HEIGHT = 128

#Identifiers
UPVOTE = "upvote"
DOWNVOTE = "downvote"
PETREPORT_PET_TYPE_DOG = "Dog"
PETREPORT_PET_TYPE_CAT = "Cat"
PETREPORT_PET_TYPE_BIRD = "Bird"
PETREPORT_PET_TYPE_HORSE = "Horse"
PETREPORT_PET_TYPE_RABBIT = "Rabbit"
PETREPORT_PET_TYPE_SNAKE = "Snake"
PETREPORT_PET_TYPE_TURTLE = "Turtle"
PETREPORT_PET_TYPE_OTHER = "Other"

#PetMatch Constants
PETMATCH_OUTCOME_NEW_PETMATCH = "NEW PETMATCH"
PETMATCH_OUTCOME_DUPLICATE_PETMATCH = "DUPCLIATE PETMATCH"
PETMATCH_OUTCOME_UPDATE = "SQL UPDATE"
PETMATCH_OUTCOME_INSERTED_IMPROPERLY = "INSERTED IMPROPERLY"
PETMATCH_THRESHOLD = 100

#General File Path Constants
PROJECT_WORKSPACE = os.path.dirname(__file__)
EPM_DIRECTORY = os.path.dirname(PROJECT_WORKSPACE)

#UserProfile File Path Constants
USERPROFILE_IMAGES_DIRECTORY = STATIC_URL + "images/userprofile/"
USERPROFILE_THUMBNAILS_DIRECTORY = USERPROFILE_IMAGES_DIRECTORY + "thumbnails/"
#USERPROFILE_IMAGES_TEST_DIRECTORY = USERPROFILE_IMAGES_DIRECTORY + "test/"
USERPROFILE_IMAGES_DEFAULTS_DIRECTORY = USERPROFILE_IMAGES_DIRECTORY + "defaults/"
USERPROFILE_IMAGES_SAMPLES_DIRECTORY = USERPROFILE_IMAGES_DIRECTORY + "samples/"
USERPROFILE_THUMBNAILS_DEFAULTS_DIRECTORY = USERPROFILE_THUMBNAILS_DIRECTORY + "defaults/"
#USERPROFILE_THUMBNAILS_TEST_DIRECTORY = USERPROFILE_THUMBNAILS_DIRECTORY + "test/"
USERPROFILE_IMAGES_DEFAULT_IMAGE = USERPROFILE_IMAGES_DEFAULTS_DIRECTORY + "anonymous.gif"
USERPROFILE_THUMBNAILS_DEFAULT_IMAGE = USERPROFILE_THUMBNAILS_DEFAULTS_DIRECTORY + "anonymous.gif"

#PetReport File Path Constants
PETREPORT_IMAGES_DIRECTORY = STATIC_URL + "images/petreport/"
PETREPORT_IMAGES_DEFAULTS_DIRECTORY = PETREPORT_IMAGES_DIRECTORY + "defaults/"
#PETREPORT_IMAGES_TEST_DIRECTORY = PETREPORT_IMAGES_DIRECTORY + "test/"
PETREPORT_IMAGES_DIFFERENT_FORMATS_DIRECTORY = PETREPORT_IMAGES_DIRECTORY + "diff_formats/"
PETREPORT_THUMBNAILS_DIRECTORY = PETREPORT_IMAGES_DIRECTORY + "thumbnails/"
#PETREPORT_THUMBNAILS_TEST_DIRECTORY = PETREPORT_THUMBNAILS_DIRECTORY + "test/"
PETREPORT_THUMBNAILS_DEFAULTS_DIRECTORY = PETREPORT_THUMBNAILS_DIRECTORY + "defaults/"
PETREPORT_IMAGES_SAMPLES_DIRECTORY = PETREPORT_IMAGES_DIRECTORY + "samples/"
PETREPORT_IMAGES_SAMPLES_DOG_DIRECTORY = PETREPORT_IMAGES_SAMPLES_DIRECTORY + "dog/"
PETREPORT_IMAGES_SAMPLES_CAT_DIRECTORY = PETREPORT_IMAGES_SAMPLES_DIRECTORY + "cat/"
PETREPORT_IMAGES_SAMPLES_BIRD_DIRECTORY = PETREPORT_IMAGES_SAMPLES_DIRECTORY + "bird/"
PETREPORT_IMAGES_SAMPLES_HORSE_DIRECTORY = PETREPORT_IMAGES_SAMPLES_DIRECTORY + "horse/"
PETREPORT_IMAGES_SAMPLES_RABBIT_DIRECTORY = PETREPORT_IMAGES_SAMPLES_DIRECTORY + "rabbit/"
PETREPORT_IMAGES_SAMPLES_SNAKE_DIRECTORY = PETREPORT_IMAGES_SAMPLES_DIRECTORY + "snake/"
PETREPORT_IMAGES_SAMPLES_TURTLE_DIRECTORY = PETREPORT_IMAGES_SAMPLES_DIRECTORY + "turtle/"
PETREPORT_IMAGES_DEFAULT_DOG_IMAGE = PETREPORT_IMAGES_DEFAULTS_DIRECTORY + "dog_silhouette.jpg"
PETREPORT_IMAGES_DEFAULT_CAT_IMAGE = PETREPORT_IMAGES_DEFAULTS_DIRECTORY + "cat_silhouette.jpg"
PETREPORT_IMAGES_DEFAULT_BIRD_IMAGE = PETREPORT_IMAGES_DEFAULTS_DIRECTORY + "bird_silhouette.jpg"
PETREPORT_IMAGES_DEFAULT_HORSE_IMAGE = PETREPORT_IMAGES_DEFAULTS_DIRECTORY + "horse_silhouette.jpg"
PETREPORT_IMAGES_DEFAULT_RABBIT_IMAGE = PETREPORT_IMAGES_DEFAULTS_DIRECTORY + "rabbit_silhouette.jpg"
PETREPORT_IMAGES_DEFAULT_SNAKE_IMAGE = PETREPORT_IMAGES_DEFAULTS_DIRECTORY + "snake_silhouette.jpg"
PETREPORT_IMAGES_DEFAULT_TURTLE_IMAGE = PETREPORT_IMAGES_DEFAULTS_DIRECTORY + "turtle_silhouette.jpg"
PETREPORT_THUMBNAILS_DEFAULT_DOG_IMAGE = PETREPORT_THUMBNAILS_DEFAULTS_DIRECTORY + "dog_silhouette.jpg"
PETREPORT_THUMBNAILS_DEFAULT_CAT_IMAGE = PETREPORT_THUMBNAILS_DEFAULTS_DIRECTORY + "cat_silhouette.jpg"
PETREPORT_THUMBNAILS_DEFAULT_BIRD_IMAGE = PETREPORT_THUMBNAILS_DEFAULTS_DIRECTORY + "bird_silhouette.jpg"
PETREPORT_THUMBNAILS_DEFAULT_HORSE_IMAGE = PETREPORT_THUMBNAILS_DEFAULTS_DIRECTORY + "horse_silhouette.jpg"
PETREPORT_THUMBNAILS_DEFAULT_RABBIT_IMAGE = PETREPORT_THUMBNAILS_DEFAULTS_DIRECTORY + "rabbit_silhouette.jpg"
PETREPORT_THUMBNAILS_DEFAULT_SNAKE_IMAGE = PETREPORT_THUMBNAILS_DEFAULTS_DIRECTORY + "snake_silhouette.jpg"
PETREPORT_THUMBNAILS_DEFAULT_TURTLE_IMAGE = PETREPORT_THUMBNAILS_DEFAULTS_DIRECTORY + "turtle_silhouette.jpg"

#Activity Log File Path Constants
ACTIVITY_LOG_DIRECTORY = STATIC_URL + "activity_logs/"

#List of sample PetReport Dog images
PETREPORT_SAMPLE_DOG_IMAGES = []
#List of sample PetReport Cat images
PETREPORT_SAMPLE_CAT_IMAGES = []
#List of sample PetReport Bird images
PETREPORT_SAMPLE_BIRD_IMAGES = []
#List of sample PetReport Horse images
PETREPORT_SAMPLE_HORSE_IMAGES = []
#List of sample PetReport Rabbit images
PETREPORT_SAMPLE_RABBIT_IMAGES = []
#List of sample PetReport Snake images
PETREPORT_SAMPLE_SNAKE_IMAGES = []
#List of sample PetReport Turtle images
PETREPORT_SAMPLE_TURTLE_IMAGES = []

#Activity Enum Values
ACTIVITY_ACCOUNT_CREATED = "ACTIVITY_ACCOUNT_CREATED"
ACTIVITY_LOGIN = "ACTIVITY_LOGIN"
ACTIVITY_LOGOUT = "ACTIVITY_LOGOUT"
ACTIVITY_PETREPORT_SUBMITTED = "ACTIVITY_PETREPORT_SUBMITTED"
ACTIVITY_PETREPORT_ADD_BOOKMARK = "ACTIVITY_PETREPORT_ADD_BOOKMARK"
ACTIVITY_PETREPORT_REMOVE_BOOKMARK = "ACTIVITY_PETREPORT_REMOVE_BOOKMARK"
ACTIVITY_PETMATCH_PROPOSED = "ACTIVITY_PETMATCH_PROPOSED"
ACTIVITY_PETMATCH_UPVOTE = "ACTIVITY_PETMATCH_UPVOTE"
ACTIVITY_PETMATCH_UPVOTE_SUCCESSFUL = "ACTIVITY_PETMATCH_UPVOTE_SUCCESSFUL"
ACTIVITY_PETMATCH_DOWNVOTE= "ACTIVITY_PETMATCH_DOWNVOTE"
ACTIVITY_FOLLOWING = "ACTIVITY_FOLLOWING"
ACTIVITY_UNFOLLOWING = "ACTIVITY_UNFOLLOWING"
ACTIVITY_FOLLOWER = "ACTIVITY_FOLLOWER"
ACTIVITY_UNFOLLOWER = "ACTIVITY_UNFOLLOWER"
ACTIVITY_PETMATCH_PROPOSED_FOR_BOOKMARKED_PETREPORT = "ACTIVITY_PETMATCH_PROPOSED_FOR_BOOKMARKED_PETREPORT"
ACTIVITY_USER_CHANGED_USERNAME = "ACTIVITY_USER_CHANGED_USERNAME"
ACTIVITY_USER_BEING_FOLLOWED = "ACTIVITY_USER_BEING_FOLLOWED"
ACTIVITY_USER_BEING_UNFOLLOWED = "ACTIVITY_USER_BEING_UNFOLLOWED"
ACTIVITY_USER_PROPOSED_PETMATCH_UPVOTE = "ACTIVITY_USER_PROPOSED_PETMATCH_UPVOTE"
ACTIVITY_USER_PROPOSED_PETMATCH_SUCCESSFUL = "ACTIVITY_USER_PROPOSED_PETMATCH_SUCCESSFUL"
ACTIVITY_USER_PROPOSED_PETMATCH_FAILURE = "ACTIVITY_USER_PROPOSED_PETMATCH_FAILURE"
ACTIVITY_USER_VERIFY_PETMATCH_SUCCESSFUL = "ACTIVITY_USER_VERIFY_PETMATCH_SUCCESSFUL"
ACTIVITY_USER_SEND_MESSAGE_TO_USERPROFILE = "ACTIVITY_USER_SEND_MESSAGE_TO_USER "

#Reputation reward points
REWARD_PETMATCH_VOTE = 2
REWARD_PETMATCH_UPVOTE_SUCCESSFUL = 10
REWARD_PETMATCH_PROPOSE = 5
REWARD_PETREPORT_SUBMIT = 5
REWARD_PETREPORT_BOOKMARK = 1
REWARD_USER_FOLLOWED = 2
#Reward this user for his/her proposed petmatch being voted
REWARD_USER_PROPOSED_PETMATCH_VOTE = 5 
REWARD_USER_PROPOSED_PETMATCH_SUCCESSFUL = 25
REWARD_USER_PROPOSED_PETMATCH_FAILURE = 15
REWARD_USER_VERIFY_PETMATCH_SUCCESSFUL = 15
REWARD_NEW_ACCOUNT = 10

#Represents how many activities to fetch per request.
ACTIVITY_FEED_LENGTH = 25

#URLS - use for redirect calls
URL_HOME = '/'
URL_GET_ACTIVITIES = "/get_activities_json"
URL_GET_PETMATCHES = "/get_PetMatches"
URL_GET_BOOKMARKS = "/get_bookmarks"
URL_LOGIN = '/login'
URL_TC = '/tc'
URL_TC_18 = '/tc_18'
URL_USERPROFILE = '/UserProfile/'
URL_SEND_MESSAGE_TO_USERPROFILE = "/UserProfile/message_UserProfile"
URL_FOLLOW = "/UserProfile/follow"
URL_UNFOLLOW = "/UserProfile/unfollow"
URL_EDITUSERPROFILE_INFO = "/UserProfile/edituserprofile/update_User_info"
URL_EDITUSERPROFILE_PWD = "/UserProfile/edituserprofile/update_User_password"
URL_EDITUSERPROFILE = "/UserProfile/edituserprofile"
URL_PRDP = '/reporting/PetReport/'
URL_SUBMIT_PETREPORT ='/reporting/submit_PetReport'
URL_BOOKMARK_PETREPORT = "/reporting/bookmark_PetReport"
URL_PMDP = '/matching/PetMatch/'
URL_VOTE_MATCH = '/matching/vote_PetMatch'
URL_MATCHING = "/matching/match_PetReport/"
URL_PROPOSE_MATCH = "/matching/propose_PetMatch/"
URL_VERIFY_PETMATCH = "/matching/verify_PetMatch/"
URL_EMAIL_VERIFICATION_COMPLETE = "/email_verification_complete/" 
URL_REGISTRATION = "/accounts/register/"
URL_REGISTRATION_COMPLETE = "/register/complete/"
URL_ACTIVATION_COMPLETE = "/accounts/activate/complete/"
URL_SOCIAL_AUTH_GET_DETAILS = "/get_social_details"
URL_SOCIAL_AUTH_COMPLETE = "/socialauth_complete"

#HTML File Paths (relative to STATIC_URL) - use for render_to_response calls
HTML_HOME = "home/index.html"
HTML_PETMATCHES = "home/petmatches.html"
HTML_BOOKMARKS = "home/bookmarks.html"
HTML_ABOUT = "home/about.html"
HTML_TC = "home/tc.html"
HTML_TC_18 = "home/tc_18.html"
HTML_USERPROFILE = "home/userprofile.html"
HTML_EDITUSERPROFILE_FORM ="home/edituserprofile_form.html"
HTML_LOGIN = "registration/login.html"
HTML_REGISTRATION_FORM = "registration/registration_form.html"
HTML_SOCIAL_AUTH_FORM = "registration/social_auth_form.html"
HTML_SUBMIT_PETREPORT = "reporting/petreport_form.html"
HTML_PRDP = "reporting/petreport.html"
HTML_PMDP = "matching/petmatch.html"
HTML_MATCHING = "matching/matching.html"
HTML_PROPOSE_MATCH = "matching/propose_match.html"
HTML_VERIFY_PETMATCH = "matching/verify_petmatch.html"

TEXTFILE_EMAIL_ACTIVATION_SUBJECT="registration/activation_email_subject.txt"
TEXTFILE_EMAIL_CHANGE_VERICATION="home/email_change_verification.txt"
TEXTFILE_EMAIL_PETOWNER_VERIFY_PETMATCH = "matching/verification_email_to_pet_owner.txt"
TEXTFILE_EMAIL_PETMATCH_PROPOSER = "matching/verification_email_to_digital_volunteer.txt"
TEXTFILE_EMAIL_USERPROFILE_MESSAGE = "home/email_message_user.txt"

#E-mail Constants
EMAIL_SUBJECT_PETOWNER_VERIFY_PETMATCH="Emergency Pet Matcher: We have found a potential match for your pet!"
EMAIL_SUBJECT_PETMATCH_PROPOSER='EmergencyPetMatcher: Your pet match is close to being successful!'
TEST_EMAIL="emergencypetmatchertest@gmail.com"


#Place sample petreport image lists in memory as global variables. Used for generating random PetReports with sample images.
def load_PetReport_sample_images():
	for img in os.listdir(PETREPORT_IMAGES_SAMPLES_DOG_DIRECTORY):
		if img != ".DS_Store" and img != ".anchor":
			PETREPORT_SAMPLE_DOG_IMAGES.append("images/petreport/samples/dog/" + img)
	for img in os.listdir(PETREPORT_IMAGES_SAMPLES_CAT_DIRECTORY):
		if img != ".DS_Store" and img != ".anchor":
			PETREPORT_SAMPLE_CAT_IMAGES.append("images/petreport/samples/cat/" + img)
	for img in os.listdir(PETREPORT_IMAGES_SAMPLES_BIRD_DIRECTORY):
		if img != ".DS_Store" and img != ".anchor":
			PETREPORT_SAMPLE_BIRD_IMAGES.append("images/petreport/samples/bird/" + img)
	for img in os.listdir(PETREPORT_IMAGES_SAMPLES_HORSE_DIRECTORY):
		if img != ".DS_Store" and img != ".anchor":
			PETREPORT_SAMPLE_HORSE_IMAGES.append("images/petreport/samples/horse/" + img)
	for img in os.listdir(PETREPORT_IMAGES_SAMPLES_RABBIT_DIRECTORY):
		if img != ".DS_Store" and img != ".anchor":
			PETREPORT_SAMPLE_RABBIT_IMAGES.append("images/petreport/samples/rabbit/" + img)
	for img in os.listdir(PETREPORT_IMAGES_SAMPLES_SNAKE_DIRECTORY):
		if img != ".DS_Store" and img != ".anchor":
			PETREPORT_SAMPLE_SNAKE_IMAGES.append("images/petreport/samples/snake/" + img)
	for img in os.listdir(PETREPORT_IMAGES_SAMPLES_TURTLE_DIRECTORY):
		if img != ".DS_Store" and img != ".anchor":
			PETREPORT_SAMPLE_TURTLE_IMAGES.append("images/petreport/samples/turtle/" + img)

