from project.settings import MEDIA_ROOT

#URLs
URL_GET_PETREPORTS_JSON = "/reporting/get_PetReports_JSON"
URL_MIXED = '/reporting/mixed'
URL_PRDP = '/reporting/'
URL_PETREPORT_FORM ='/reporting/new'
URL_SUBMIT_PETREPORT="/reporting/submit"
URL_EDIT_PETREPORT ='/reporting/edit/'
URL_GET_PET_BREEDS = "/reporting/get_pet_breeds"
URL_BOOKMARK_PETREPORT = "/reporting/bookmark"
URL_CLOSE_PETREPORT = "/reporting/close/"

HTML_PETREPORT_FORM = "reporting/petreport_form.html"
HTML_PRDP = "reporting/petreport.html"
HTML_EDIT_PETREPORT = "reporting/edit_petreport.html"

#number of pet reports on the home page
NUM_PETREPORTS_HOMEPAGE = 25

#number of bookmarks on the home page
NUM_BOOKMARKS_HOMEPAGE = 25

#Lower and Upper bounds for Lost and Found Dates
DATE_LOWER_BOUND = "2012-01-01"
DATE_UPPER_BOUND = "2012-08-16"


#Email Constants.
EMAIL_SUBJECT_MATCH_BY_MICROCHIP_ID = "We may have found a potential match for your pet!"
EMAIL_BODY_MATCH_BY_MICROCHIP_ID = "reporting/email_match_by_microchip_id.txt"

#Enums for Various Model Choice Fields
PET_TYPE_CHOICES = [('Dog', 'Dog'), ('Cat', 'Cat'), ('Bird', 'Bird'), ('Horse', 'Horse'), ('Rabbit', 'Rabbit'), ('Snake', 'Snake'), ('Turtle', 'Turtle'), ('Other', 'Other')]
STATUS_CHOICES = [('Lost','Lost'),('Found','Found')]
SEX_CHOICES=[('Male','Male'),('Female','Female')]
SIZE_CHOICES = [('Extra Large', 'Extra Large'),('Large', 'Large'), ('Medium', 'Medium'), ('Small', 'Small')]
SPAYED_OR_NEUTERED_CHOICES = [("Not Known", "Not Known"),('Spayed', 'Spayed'), ('Neutered', 'Neutered'), ("Neither", "Neither")]
AGE_CHOICES = [('Baby','Baby'),('Young','Young'),('Adult','Adult'),('Senior','Senior'),("Not Known", "Not Known")]

PETREPORT_NAMES = ['Sparky', 'Nugget', 'Sydney', 'Missy', 'Marley', 'Fousey', 'Daisy', 'Libby', 'Apollo', 'Buster', 'Izzy', 'Bentley', 'Scruffy', 'Dandy', 'Candy', 'Mark', 'Baby', 'Toodle', 'Princess' ,'Prince', 'Guss', 'Rocket', 'Darling']

PETREPORT_PET_TYPE_LENGTH = 10
PETREPORT_STATUS_LENGTH = 5
PETREPORT_SEX_LENGTH = 6
PETREPORT_SIZE_LENGTH = 30
PETREPORT_EVENT_TAG_LENGTH = 100
PETREPORT_LOCATION_LENGTH = 100
PETREPORT_PET_NAME_LENGTH = 30
PETREPORT_MICROCHIP_ID_LENGTH = 40
PETREPORT_TAG_INFO_LENGTH = 500
PETREPORT_CONTACT_NAME_LENGTH = 50
PETREPORT_CONTACT_NUMBER_LENGTH = 30
PETREPORT_CONTACT_EMAIL_LENGTH = 50
PETREPORT_CONTACT_LINK_LENGTH = 300
PETREPORT_AGE_LENGTH = 10
PETREPORT_COLOR_LENGTH =30
PETREPORT_BREED_LENGTH = 90
PETREPORT_DESCRIPTION_LENGTH = 1000
PETREPORT_SPAYED_OR_NEUTERED_LENGTH = 10

PETREPORT_PET_TYPE_DOG = "Dog"
PETREPORT_PET_TYPE_CAT = "Cat"
PETREPORT_PET_TYPE_HORSE = "Horse"
PETREPORT_PET_TYPE_BIRD = "Bird"
PETREPORT_PET_TYPE_RABBIT = "Rabbit"
PETREPORT_PET_TYPE_SNAKE = "Snake"
PETREPORT_PET_TYPE_TURTLE = "Turtle"
PETREPORT_PET_TYPE_OTHER = "Other"

#PetReport Image Paths
PETREPORT_IMG_PATH = "petreport/uploads/"
PETREPORT_THUMBNAIL_PATH = "petreport/thumbnails/"

#PetReport File Path Constants
PETREPORT_MEDIA_DIRECTORY = MEDIA_ROOT + "petreport/"

#Top-level PetReport subdirectory constants
PETREPORT_BREEDS_DIRECTORY = PETREPORT_MEDIA_DIRECTORY + "breeds/"
PETREPORT_IMAGES_DIFFERENT_FORMATS_DIRECTORY = PETREPORT_MEDIA_DIRECTORY + "diff_formats/"
PETREPORT_SAMPLES_DIRECTORY = PETREPORT_MEDIA_DIRECTORY + "samples/"
PETREPORT_THUMBNAILS_DIRECTORY = PETREPORT_MEDIA_DIRECTORY + "thumbnails/"
PETREPORT_UPLOADS_DIRECTORY = PETREPORT_MEDIA_DIRECTORY + "uploads/"

#Defaults Directories (for PetReport image uploads and their thumbnails)
PETREPORT_THUMBNAILS_DEFAULTS_DIRECTORY = PETREPORT_THUMBNAILS_DIRECTORY + "defaults/"
PETREPORT_UPLOADS_DEFAULTS_DIRECTORY = PETREPORT_UPLOADS_DIRECTORY + "defaults/"

#Breeds
PETREPORT_BREED_DOG_FILE = PETREPORT_BREEDS_DIRECTORY + "dogs.txt"
PETREPORT_BREED_CAT_FILE = PETREPORT_BREEDS_DIRECTORY + "cats.txt"
PETREPORT_BREED_HORSE_FILE = PETREPORT_BREEDS_DIRECTORY + "horses.txt"
PETREPORT_BREED_BIRD_FILE = PETREPORT_BREEDS_DIRECTORY + "birds.txt"
PETREPORT_BREED_RABBIT_FILE = PETREPORT_BREEDS_DIRECTORY + "rabbits.txt"
PETREPORT_BREED_TURTLE_FILE = PETREPORT_BREEDS_DIRECTORY + "turtles.txt"
PETREPORT_BREED_SNAKE_FILE = PETREPORT_BREEDS_DIRECTORY + "snakes.txt"
PETREPORT_BREED_OTHER_FILE = PETREPORT_BREEDS_DIRECTORY + "other.txt"

#Defaults
PETREPORT_UPLOADS_DEFAULT_DOG_IMAGE =  PETREPORT_IMG_PATH + "defaults/dog_silhouette.jpg"
PETREPORT_UPLOADS_DEFAULT_CAT_IMAGE =  PETREPORT_IMG_PATH + "defaults/cat_silhouette.jpg"
PETREPORT_UPLOADS_DEFAULT_BIRD_IMAGE =  PETREPORT_IMG_PATH + "defaults/bird_silhouette.jpg"
PETREPORT_UPLOADS_DEFAULT_HORSE_IMAGE =  PETREPORT_IMG_PATH + "defaults/horse_silhouette.jpg"
PETREPORT_UPLOADS_DEFAULT_RABBIT_IMAGE =  PETREPORT_IMG_PATH + "defaults/rabbit_silhouette.jpg"
PETREPORT_UPLOADS_DEFAULT_SNAKE_IMAGE =  PETREPORT_IMG_PATH + "defaults/snake_silhouette.jpg"
PETREPORT_UPLOADS_DEFAULT_TURTLE_IMAGE =  PETREPORT_IMG_PATH + "defaults/turtle_silhouette.jpg"
PETREPORT_UPLOADS_DEFAULT_OTHER_IMAGE =  PETREPORT_IMG_PATH + "defaults/other_silhouette.jpg"

#Samples
PETREPORT_SAMPLES_DOG_DIRECTORY = PETREPORT_SAMPLES_DIRECTORY + "dog/"
PETREPORT_SAMPLES_CAT_DIRECTORY = PETREPORT_SAMPLES_DIRECTORY + "cat/"
PETREPORT_SAMPLES_BIRD_DIRECTORY = PETREPORT_SAMPLES_DIRECTORY + "bird/"
PETREPORT_SAMPLES_HORSE_DIRECTORY = PETREPORT_SAMPLES_DIRECTORY + "horse/"
PETREPORT_SAMPLES_RABBIT_DIRECTORY = PETREPORT_SAMPLES_DIRECTORY + "rabbit/"
PETREPORT_SAMPLES_SNAKE_DIRECTORY = PETREPORT_SAMPLES_DIRECTORY + "snake/"
PETREPORT_SAMPLES_TURTLE_DIRECTORY = PETREPORT_SAMPLES_DIRECTORY + "turtle/"

#Thumbnail Defaults
PETREPORT_THUMBNAILS_DEFAULT_DOG_IMAGE = PETREPORT_THUMBNAIL_PATH + "defaults/dog_silhouette.jpg"
PETREPORT_THUMBNAILS_DEFAULT_CAT_IMAGE = PETREPORT_THUMBNAIL_PATH + "defaults/cat_silhouette.jpg"
PETREPORT_THUMBNAILS_DEFAULT_BIRD_IMAGE = PETREPORT_THUMBNAIL_PATH + "defaults/bird_silhouette.jpg"
PETREPORT_THUMBNAILS_DEFAULT_HORSE_IMAGE = PETREPORT_THUMBNAIL_PATH + "defaults/horse_silhouette.jpg"
PETREPORT_THUMBNAILS_DEFAULT_RABBIT_IMAGE = PETREPORT_THUMBNAIL_PATH + "defaults/rabbit_silhouette.jpg"
PETREPORT_THUMBNAILS_DEFAULT_SNAKE_IMAGE = PETREPORT_THUMBNAIL_PATH + "defaults/snake_silhouette.jpg"
PETREPORT_THUMBNAILS_DEFAULT_TURTLE_IMAGE = PETREPORT_THUMBNAIL_PATH + "defaults/turtle_silhouette.jpg"
PETREPORT_THUMBNAILS_DEFAULT_OTHER_IMAGE = PETREPORT_THUMBNAIL_PATH + "defaults/other_silhouette.jpg"

#Sample Lists
PETREPORT_SAMPLE_DOG_IMAGES = []
PETREPORT_SAMPLE_CAT_IMAGES = []
PETREPORT_SAMPLE_BIRD_IMAGES = []
PETREPORT_SAMPLE_HORSE_IMAGES = []
PETREPORT_SAMPLE_RABBIT_IMAGES = []
PETREPORT_SAMPLE_SNAKE_IMAGES = []
PETREPORT_SAMPLE_TURTLE_IMAGES = []

#PetReport Image constants
PETREPORT_THUMBNAIL_WIDTH = 128
PETREPORT_THUMBNAIL_HEIGHT = 128
